name: summer25
channels:
  - defaults
dependencies:
  - pip=25.1
  - python=3.10.16
  - pip:
      - accelerate==1.8.1
      - audiomentations==0.41.0
      - decorator==5.2.1
      - gcsfs==2025.7.0
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - google-auth-oauthlib==1.2.2
      - google-cloud-core==2.4.3
      - google-cloud-storage==3.2.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - huggingface-hub==0.32.4
      - librosa==0.10.2.post1
      - numpy==2.2.6
      - pandas==2.3.0
      - peft==0.15.2
      - pytest==8.4.0
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - torch==2.7.0
      - torchaudio==2.7.0
      - torchvision==0.22.0
      - tqdm==4.67.1
      - transformers==4.52.4


      
      

